### ISSUE TITLE
Build fails with conda-build 2.1+

### ISSUE THREAD

**Issue by nehaljwani** [conda-forge/metis-feedstock#10]
```python
...
updating: metis-5.1.0-3.tar.bz2                                                                                                                                                                       
updating index in: /home/nwani/m3/conda-bld
Traceback (most recent call last):
  File "/home/nwani/m3/bin/conda-build", line 6, in <module>
    sys.exit(conda_build.cli.main_build.main())
  File "/home/nwani/m3/lib/python2.7/site-packages/conda_build/cli/main_build.py", line 334, in main
    execute(sys.argv[1:])
  File "/home/nwani/m3/lib/python2.7/site-packages/conda_build/cli/main_build.py", line 325, in execute
    noverify=args.no_verify)
  File "/home/nwani/m3/lib/python2.7/site-packages/conda_build/api.py", line 97, in build
    need_source_download=need_source_download, config=config)
  File "/home/nwani/m3/lib/python2.7/site-packages/conda_build/build.py", line 1524, in build_tree
    test(pkg, config=config)
  File "/home/nwani/m3/lib/python2.7/site-packages/conda_build/build.py", line 1277, in test
    warn_on_use_of_SRC_DIR(metadata)
  File "/home/nwani/m3/lib/python2.7/site-packages/conda_build/build.py", line 1226, in warn_on_use_of_SRC_DIR
    raise ValueError("In conda-build 2.1+, the work dir is removed by default before the "
ValueError: In conda-build 2.1+, the work dir is removed by default before the test scripts run.  You are using the SRC_DIR variable in your test script, but these files have been deleted.  Please see the  docum
entation regarding the test/source_files meta.yaml section, or pass the --no-remove-work-dir flag.
```

**Comment by jakirkham** [comment]
Thanks. Should be good now.
